<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestClick.DataAccess\TestClick.DataAccess.csproj" />
    <ProjectReference Include="..\TestClick.Interface\TestClick.Interface.csproj" />
    <ProjectReference Include="..\TestClick.Model\TestClick.Model.csproj" />
  </ItemGroup>

</Project>
